Compute
Serial* Compute::serial
The serial driver instance.
Referenced by Compute, IsConnected, Update.
PID* Compute::pidX
PID for X coordinate.
Referenced by Compute, getPIDX, Update.
PID* Compute::pidY
PID for Y coordinate.
Referenced by Compute, getPIDY, Update.
Kalman* Compute::kalmanX
Kalman filter for X coordinate.
Referenced by Compute, Update.
Kalman* Compute::kalmanY
Kalman filter for X coordinate.
Referenced by Compute, Update.
int Compute::width
Camera frame width.
Referenced by Compute, center, Update, Plot.
int Compute::height
Camera frame height.
Referenced by Compute, center, Update, Plot.
int Compute::setPoint_x
X coordinate of the set point.
Referenced by Compute, setPoint, center, Update, Plot.
int Compute::setPoint_y
Y coordinate of the set point.
Referenced by Compute, setPoint, center, Update, Plot.
char* Compute::window
The window used to draw the graph.
Referenced by Compute, SetPlotter, Plot.
IplImage* Compute::image
The image used for plotting data.
Referenced by Compute, SetPlotter, Plot.
int Compute::sample
Plot x value.
Referenced by Compute, Plot.
void Compute::Plot(float x_est, float y_est)
Draw a XY plot.
This function draws a XY plot of Kalman estimation comparing values with the given set point. x_est the Kalman estimation of the x position. y_est the Kalman estimation of the y position.
References map, width, image, setPoint_x, height, setPoint_y, sample, window.
Referenced by Update.
Compute::Compute(int width, int height)
The constructor.
width Camera frame width. height Camera frame height.
References serial, pidX, pidY, kalmanX, kalmanY, width, height, setPoint_x, setPoint_y, image, window, sample.
Compute::~Compute()
The destructor.
PID * Compute::getPIDX()
Return PID x axis.
The PID instance.
References pidX.
PID * Compute::getPIDY()
Return PID y axis.
The PID instance.
References pidY.
void Compute::setPoint(int x, int y)
Update the x,y coordinates of the set point.
x x axis coordinate of the set point. y y axis coordinate of the set point.
References setPoint_x, setPoint_y.
Referenced by main.
void Compute::center()
Reset the set point to the center.
References setPoint_x, width, setPoint_y, height.
Referenced by main.
bool Compute::IsConnected()
Check serial connection.
TRUE if serial port has been connected, FALSE otherwise.
References serial, Serial::IsConnected.
Referenced by main.
void Compute::Update(int x, int y)
Main control function.
This function is responsible for the control of the plate: it makes an estimation of the real position of the object, then generate control signals (i.e. angles for each servos) using PIDs. x object x coordinate. y object y coordinate.
References serial, Serial::IsConnected, kalmanX, Kalman::update, kalmanY, pidX, PID::updatePID, setPoint_x, pidY, setPoint_y, map, MAX_ANGLE, width, height, Serial::WriteData, Plot.
Referenced by main.
void Compute::SetPlotter(char *, IplImage *)
Set OpenCV output window and image.
win the plotter window to set. image the output image to set.
References image, window.
Referenced by main.