Serial
HANDLE Serial::hSerial
Serial handler.
Referenced by Serial, ~Serial, ReadData, WriteData.
bool Serial::connected
Connection status.
Referenced by Serial, ~Serial, IsConnected.
COMSTAT Serial::status
Information about the connection.
Referenced by ReadData, WriteData.
DWORD Serial::errors
Last error.
Referenced by Serial, ReadData, WriteData.
Serial::Serial(char *portName)
The Constructor.
Initialize Serial communication with the given COM port. portName The serial port to initializa.
References connected, errors, hSerial, WAIT_TIME.
Serial::~Serial()
The destructor.
Close the serial connection.
References connected, hSerial.
int Serial::ReadData(char *buffer, unsigned int nbChar)
Read data from serial port.
buffer the destination buffer. nbChar the number of bytes to read. the number of bytes read. -1 if nothing to read.
References hSerial, errors, status.
bool Serial::WriteData(char *buffer, unsigned int nbChar)
Write data to serial port.
buffer the source buffer. nbChar the number of bytes to write. TRUE if write operation succeeded, FALSE otherwise.
References hSerial, errors, status.
Referenced by Compute::Update.
bool Serial::IsConnected()
Get the connection status.
TRUE if serial port has been connected, FALSE otherwise.
References connected.
Referenced by Compute::IsConnected, Compute::Update.