Control
MAX_ANGLE
Max servo angle absolute value.
Referenced by Compute::Update.
map
Scale an input value within a given range.
in the value to scale. inMin the lower bound of input value. inMax the upper bound of input value. outMin the lower bound of output value. outMax the upper bound of utput value. the scaled value.
Referenced by Compute::Update, Compute::Plot.
constrain
Constrain a value within a range.
value the value to constrain. min lower range limit. max upper range limit. The constrained value. value if the value is within the given range. min if the value exceeds lower range bound max if the value exceeds upper range bound
Referenced by PID::updatePID.
Compute::Compute(int width, int height)
The constructor.
width Camera frame width. height Camera frame height.
References Compute::serial, Compute::pidX, Compute::pidY, Compute::kalmanX, Compute::kalmanY, Compute::width, Compute::height, Compute::setPoint_x, Compute::setPoint_y, Compute::image, Compute::window, Compute::sample.
Compute::~Compute()
The destructor.
PID * Compute::getPIDX()
Return PID x axis.
The PID instance.
References Compute::pidX.
PID * Compute::getPIDY()
Return PID y axis.
The PID instance.
References Compute::pidY.
void Compute::setPoint(int x, int y)
Update the x,y coordinates of the set point.
x x axis coordinate of the set point. y y axis coordinate of the set point.
References Compute::setPoint_x, Compute::setPoint_y.
Referenced by main.
void Compute::center()
Reset the set point to the center.
References Compute::setPoint_x, Compute::width, Compute::setPoint_y, Compute::height.
Referenced by main.
bool Compute::IsConnected()
Check serial connection.
TRUE if serial port has been connected, FALSE otherwise.
References Compute::serial, Serial::IsConnected.
Referenced by main.
void Compute::Update(int x, int y)
Main control function.
This function is responsible for the control of the plate: it makes an estimation of the real position of the object, then generate control signals (i.e. angles for each servos) using PIDs. x object x coordinate. y object y coordinate.
References Compute::serial, Serial::IsConnected, Compute::kalmanX, Kalman::update, Compute::kalmanY, Compute::pidX, PID::updatePID, Compute::setPoint_x, Compute::pidY, Compute::setPoint_y, map, MAX_ANGLE, Compute::width, Compute::height, Serial::WriteData, Compute::Plot.
Referenced by main.
void Compute::SetPlotter(char *, IplImage *)
Set OpenCV output window and image.
win the plotter window to set. image the output image to set.
References Compute::image, Compute::window.
Referenced by main.
void Compute::Plot(float x_est, float y_est)
Draw a XY plot.
This function draws a XY plot of Kalman estimation comparing values with the given set point. x_est the Kalman estimation of the x position. y_est the Kalman estimation of the y position.
References map, Compute::width, Compute::image, Compute::setPoint_x, Compute::height, Compute::setPoint_y, Compute::sample, Compute::window.
Referenced by Compute::Update.
Kalman::Kalman(float Q, float R)
The constructor.
Q Estimation of the noise covariance. R Estimation of the noise covariance.
References Kalman::Q, Kalman::R, Kalman::x_est_last, Kalman::P_last, Kalman::K, Kalman::P, Kalman::P_temp, Kalman::x_temp_est, Kalman::x_est.
Kalman::~Kalman()
The destructor.
float Kalman::update(float measure)
Update estimated value.
measure The measured value The estimated value.
References Kalman::x_temp_est, Kalman::x_est_last, Kalman::P_temp, Kalman::P_last, Kalman::Q, Kalman::K, Kalman::R, Kalman::x_est, Kalman::P.
Referenced by Compute::Update.
PID::PID(float P, float I, float D)
The constructor.
P Proportional gain. I Integral gain. D Derivative gain.
References PID::firstPass, PID::I, PID::P, PID::D, PID::previousPIDTime, PID::lastPosition, PID::windupGuard, PID::integratedError.
PID::~PID()
The destructor.
void PID::setP(float val)
Set P value.
val the value to set.
References PID::P.
void PID::setD(float val)
Set D value.
val the value to set.
References PID::D.
void PID::setI(float val)
Set I value.
val the value to set.
References PID::I.
float PID::updatePID(float targetPosition, float currentPosition)
PID controller update function.
Compute the PID output according to the current reference signal value and the desired target reference value. targetPosition the target reference value. currentPosition current signal value. the actuator input signal needed to reach the target reference value.
References PID::previousPIDTime, PID::firstPass, constrain, PID::windupGuard, PID::integratedError, PID::D, PID::lastPosition, PID::P, PID::I.
Referenced by Compute::Update.