BallBalancing
PWMConfig pwmcfg
PWM configuration structure.
Channels 3 and 4 enabled without callbacks, the active state is logic high.
Referenced by main.
void commandServo(uint8_t servo, int8_t angle)
Rotate a servo with the given angle.
servo the servo to command (0 or 1). angle the rotation angle in the range [-MAX_ANGLE,MAX_ANGLE]. the servo id will be mapped to the associated PWM channel.
References MAX_ANGLE, map, MIN_SERVO, MAX_SERVO.
Referenced by CtrlThread, main.
static WORKING_AREA(ctrlThreadWA, 128)
The servo control thread.
It reads the angle used to control the servos from serial driver, then it commands the servo. arg the thread argument. the thread exit status. serial 1° byte --> servo 0 angle, serial 2° byte --> servo 1 angle.
static msg_t CtrlThread(void *arg)
References MAX_ANGLE, commandServo.
Referenced by main.
int main(void)
Application entry point.
References pwmcfg, commandServo, CtrlThread.
MIN_SERVO
HS325HB servo min pulse.
Referenced by commandServo.
MAX_SERVO
HS325HB servo max pulse.
Referenced by commandServo.
MAX_ANGLE
HS325HB servo max absolute angle.
Referenced by commandServo, CtrlThread.
map
Scale an input value within a given range.
in the value to scale. inMin the lower bound of input value. inMax the upper bound of input value. outMin the lower bound of output value. outMax the upper bound of utput value. the scaled value.
Referenced by commandServo.